FROM debian:stretch

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    g++ \
    make \
    python3

ENV PATH="/usr/local/bin:$PATH"

# libbuffer source gets copied here
WORKDIR /libbuffer-build
COPY . .
